[package]
name = "client_hello"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_primitive = "0.1.1"
num = "0.4.0"
hex-slice = "0.1.4"
rust-crypto = "0.2.36"
byteorder = "1.4.3"
hex = "0.4.3"